version: 2
jobs:

  build_linux:
    working_directory: ~/angular-electron
    docker:
      - image: circleci/node:15.14.0
    steps:
      - checkout
      - run: cd angular-electron && npm install
      - run: cd angular-electron && npm run build;
      - run: cd angular-electron && npm run deploy:linux;

  build_windows:
    working_directory: ~/angular-electron
    docker:
      - image: electronuserland/builder:wine
    steps:
      - checkout
      - run: cd angular-electron && npm install;
      - run: cd angular-electron && npm install -g @angular/cli;
      - run: cd angular-electron && npm run build;
      - run: cd angular-electron && npm run deploy:win;

workflows:
  version: 2

  build:
    jobs:
      - build_windows
      - build_linux 