version: 2
jobs: 
  
  build_windows:
    docker:
      - image: electronuserland/builder:wine
    steps:
      - checkout
      - run: cd angular-electron && npm install;
      - run: cd angular-electron && npm install -g @angular/cli;
      - run: cd angular-electron && npm run build;
      - run: cd angular-electron && npm run deploy:win;
      
  build_linux:
    docker:
       - image: circleci/node:15.14.0
    steps:
      - checkout
      - run: sudo npm install -g npm
      - run: cd angular-electron && sudo npm install;
      - run: cd angular-electron && sudo npm install -g @angular/cli;
      - run: cd angular-electron && sudo npm run build;
      - run: cd angular-electron && sudo npm run deploy:win;
      
  build_macos:
    macos:
      xcode: "11.3"
    steps:
      - checkout
      - run: security create-keychain -p $KEYCHAIN_PASSWORD build.keychain
      - run: security default-keychain -s build.keychain
      - run: security unlock-keychain -p $KEYCHAIN_PASSWORD build.keychain
      - run: echo $KEYSTORE | base64 --decode - > keystore.p12
      - run: security import keystore.p12 -k build.keychain -P $KEYCHAIN_PASSWORD -T /usr/bin/codesign
      - run: cd angular-electron && npm install;
      - run: cd angular-electron && npm install -g @angular/cli;
      - run: cd angular-electron && npm run build;
      - run: cd angular-electron && npm run deploy:win;

workflows:
  version: 2
  
  build:
    jobs:
      - build_windows
      - build_linux
      - build_macos