version: 2
jobs:
  build:
    working_directory: ~/angular-electron
    docker:
      - image: circleci/node:15.14.0
    steps:
      - checkout
      # - restore_cache:
      #     key: AngularCircleCI-{{ .Branch }}-{{ checksum "package.json" }}
      - run: cd angular-electron && npm install
      # - save_cache:
      #     key: AngularCircleCI-{{ .Branch }}-{{ checksum "package.json" }}
      #     paths:
      #       - "node_modules"
      - run: cd angular-electron && npm run build;
      - run: cd angular-electron && npm run deploy:win;
      - run: cd angular-electron && npm run deploy:linux;